name: Deploy to ECS

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::838979473447:role/githubactions-role
        aws-region: us-east-1

    - name: Login to Amazon ECR (manual)
      run: |
        aws ecr get-login-password --region us-east-1 \
        | docker login \
          --username AWS \
          --password-stdin 838979473447.dkr.ecr.us-east-1.amazonaws.com

    - name: Build & Push Docker Image
      env:
        ECR_REPO: ecs-demo
        AWS_ACCOUNT_ID: 838979473447
        AWS_REGION: us-east-1
      run: |
        IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

    - name: Deploy ECS Service
      run: |
        aws ecs update-service \
          --cluster ecs-demo-cluster \
          --service ecs-demo-service \
          --force-new-deployment
